### ISSUE TITLE
suggestions not shown in some cases (inline fields with brackets)

### ISSUE THREAD

**Issue by Rhydderch** [dsarman/better-inline-fields#5] opened 2022-11-06 06:31 UTC
Hello,
Thank you very much for the update that supports inline fields in between brackets.

I stumbled upon some bugs:

`[inline:: start-typing]` : if the brackets were already there, no suggestions are shown
`[ inline:: start-typing]` : if I put a space before the field, then it works and suggestions are shown
`[inline:: start-typing` : if there is no space before the field, but not closing bracket, then suggestions are shown

For me, the expected behavior would be that it works in the case `[inline:: start-typing]`, otherwise it loses compatibility with other plugins.

**Comment by dsarman** [comment] 2022-11-06 11:40
Hi, thanks for the report.
As for the individual cases:
1. `[inline:: start-typing]` should work. Here is a gif, am I doing something differently there?
![inline_bracketed_complete](https://user-images.githubusercontent.com/10750070/200168320-1dc8311e-4a81-4317-8a4a-7f5f0a80e430.gif)
3. `[ inline:: start-typing]` that is a known bug that I will fix later. The impact is low and fixing would take more time than I have right now.
4. `[inline:: start-typing` this is a feature, not a bug. I want to support the case where you start writing the inline field without the closing bracket, use the autocomplete, and only after that type out the closing bracket.

**Closed as not planned** 2023-08-24 20:20 UTC
